var aDovgal = {
    "first-name": "ALEKSANDR", //name
    "last-name": "DOVGAL", //name
    "job": "Senior IT Project Manager",
    "industry": "IT", //skip
    "birthday": "29th August 1978",
    "address": "Ukraine",
    "tel": "+38 (050) 964 21 58",
    "email": "adovgal78@gmail.com",
    "url": "adovgal.com",
    "skype": "adovgal78",
    "linkedin": "https://www.linkedin.com/in/adovgal78/",
    "facebook": "https://www.facebook.com/adovgal78/",
    "summary": "Always kept deadlines",
    "achievement1": "Experience",
    "valueachievement1": "15 years",
    "achievement2": "Completed projects",
    "valueachievement2": "20 projects",
    "achievement3": "Automated workplaces",
    "valueachievement3": "1000 workplaces",
    "1experience1": "UpWork",
    "1valueexperience1": "2017 - Present",
    "2experience1": "Freelancer",
    "2valueexperience1": "JavaScript, CSS, HTML\nWordPress\nDivi",
    "1experience2": "InterSoft",
    "1valueexperience2": "2015 - 2016",
    "2experience2": "Chief executive officer",
    "2valueexperience2": "Making high-level decisions\nEssential management\nCommunication role",
    "1experience3": "InterSoft",
    "1valueexperience3": "2007-2014",
    "2experience3": "Chief technology officer",
    "2valueexperience3": "Technical vision\nProduction\nEnd-user responsibility",
    "1experience4": "InterSoft",
    "1valueexperience4": "2005-2006",
    "2experience4": "Head of implementation dep",
    "2valueexperience4": "Implementation\nQuality assurance\nUser support",
    "1experience5": "InterSoft",
    "1valueexperience5": "2003-2004",
    "2experience5": "Analytic",
    "2valueexperience5": "Consulting services\nReview system issues",
    "skills1": "PMBOK",
    "valueskills1": "75%",
    "skills2": "BPMN",
    "valueskills2": "90%",
    "skills3": "MS Project",
    "valueskills3": "80%",
    "skills4": "SCRUM",
    "valueskills4": "85%",
    "skills5": "XMIND",
    "valueskills5": "95%",
    "education1": "Kharkiv National University of Radio Electronics",
    "valueeducation1": "Master of computer Sciences",
    "languages1": "English",
    "valuelanguages1": "advanced",
    "languages2": "Ukrainian",
    "valuelanguages2": "fluent",
    "languages3": "Russian",
    "valuelanguages3": "native"
};